.PHONY: clean All

All:
	@echo "----------Building project:[ absolutecpp - Debug ]----------"
	@cd "absolutecpp" && "$(MAKE)" -f  "absolutecpp.mk"
clean:
	@echo "----------Cleaning project:[ absolutecpp - Debug ]----------"
	@cd "absolutecpp" && "$(MAKE)" -f  "absolutecpp.mk" clean
